# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Group8Application' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Group8Application
  pod 'CocoaMQTT'

end

target 'Group8Application WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Group8Application WatchKit App

end

target 'Group8Application WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Group8Application WatchKit Extension

end
